### ISSUE TITLE
Outerloop needs args in config file

### ISSUE THREAD

**Issue by annarafferty** [apprenticelearner/AL_HTML#5]
AL_HTML should pass something like a "controller_args" into the constructor for the outerloop controller, so that it doesn't need a separate config file.

**Comment by eharpste** [comment]
Can we create a corresponding issue on AL_outerloop?

**Comment by cmaclell** [comment]
It looks like someone created one here: https://github.com/apprenticelearner/AL_outerloop/issues/2
